# Generated by Django 5.1.2 on 2025-06-01 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('context', models.CharField(choices=[('legal', 'Legal'), ('work', 'Work'), ('social', 'Social'), ('religious', 'Religious')], max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('visibility_roles', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
