# Generated by Django 5.1.2 on 2025-06-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identity',
            old_name='display_name',
            new_name='display_name_en',
        ),
        migrations.AddField(
            model_name='identity',
            name='display_name_zh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
