# Generated by Django 5.1.2 on 2025-06-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_display_name_identity_display_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr', 'HR'), ('friend', 'Friend'), ('owner', 'Owner')], default='friend', max_length=20),
        ),
    ]
