# Generated by Django 5.1.2 on 2025-06-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identity',
            name='visibility_roles',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
