# Generated by Django 5.1.2 on 2025-06-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_identity_visibility_roles_alter_profile_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identity',
            old_name='display_name_en',
            new_name='display_name',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='display_name_zh',
        ),
        migrations.AlterField(
            model_name='identity',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('zh', 'Chinese'), ('ms', 'Malay'), ('ta', 'Tamil')], default='en', max_length=10),
        ),
    ]
