# Generated by Django 5.1.2 on 2025-09-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_display_name_en_identity_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='context',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='identity',
            name='language',
            field=models.CharField(default='en', max_length=20),
        ),
    ]
