# Generated by Django 5.1.2 on 2025-09-07 16:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_identity_context_alter_identity_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='identity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
