# Generated by Django 5.1.2 on 2025-09-08 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_profile_gender_identity_profile_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by', to='core.identity'),
        ),
    ]
